### ISSUE TITLE
no repo Tags

### ISSUE THREAD

**Issue by MentalGear** [tauri-apps/tauri-plugin-fs-extra#38]
Installing via 
`yarn add github:tauri-apps/tauri-plugin-fs-extra#v0.1.0`

won't work since the repo has no tags defined.

**Comment by DashCruft** [comment]
Just use 

`yarn add github:tauri-apps/tauri-plugin-fs-extra` 

That should be enough.

**Comment by JonasKruckenberg** [comment]
We will properly publish all plugins soon, you this issues will be fully resolved then
